### ISSUE TITLE
[Enhancement] Use the Minecraft platform ID

### ISSUE THREAD

**Issue by Itay080** [TouwaStar/Galaxy_Plugin_Minecraft#1]
The Minecraft platform ID has been added to the API
https://github.com/gogcom/galaxy-integrations-python-api/commit/8d6ec500f97e74efd709902cad2447dafc1b7397

**Comment by TouwaStar** [comment]
It looks like it was added to the api but the client itself doesnt handle it yet?

Its not showing up in my client after changing and i can see this in GalaxyClient.log

2019-09-06 09:30:43.983 [Warning][ (0)] [TID 16332][galaxy_client]: Failed to parse plugin manifest, exception: Unrecognized SupportedPlatform value: minecraft

**Comment by Itay080** [comment]
You're right, it's not yet implemented in the client. Sorry for misleading you!

**Comment by ghost** [comment]
release 0.49 added minecraft definition

**Comment by TouwaStar** [comment]
should work correctly in https://github.com/TouwaStar/Galaxy_Plugin_Minecraft/commit/178d31bda38e9d6b490afbe0b8674864141a44c4 

download plugin anew to confirm
