### ISSUE TITLE
Plugin logs in as Minecraft Player

### ISSUE THREAD

**Issue by OldShaterhan** [TouwaStar/Galaxy_Plugin_Minecraft#12]
Hi all,
I'm trying to connect Minecraft to GOG Galaxy connections, but for some reason - when confirming possibilities I'm not asked for any credentials, etc. instead I'm automatically logged in as "Minecraft Player". I don't think this is a proper behaviour for this plugin? Before connection I was logged out of plugin and such behaviour happened, but also after logging to Minecraft Launcher and then running integrations results in the same.
![image](https://user-images.githubusercontent.com/1622866/94868109-d43c3400-0442-11eb-92c2-b31662f5d392.png)

**Comment by TouwaStar** [comment]
Hi,
Minecraft integration doesn't need your minecraft/mojang credentials for any of its functionalities thats why you are not asked to sign in.
