### ISSUE TITLE
By specifying main-content height to be 269px, the Continue button becomes unclickable and the entire footer is hidden behind mc.jpg (which is 465 pixels tall in itself)

### ISSUE THREAD

**Issue by 3ICE** [TouwaStar/Galaxy_Plugin_Minecraft#14]
Hi, The Continue button should be shoved under the pictures, not hidden behind them.

Screenshot:
![image](https://user-images.githubusercontent.com/5385790/103375779-47555500-4adb-11eb-8635-da111223b4cf.png)

The little purple thingy in the bottom left corner is the button users are supposed to click. Nearly impossible.

No, I do not use Windows system magnification. (The issue would become even worse then.)
My screen resolution however, is below 1080p, at1600×900.

--3ICE

**Comment by urwrstkn8mare** [comment]
Thanks @3ICE! I've updated it so it should fix this little issue. Until [the pull request](https://github.com/TouwaStar/Galaxy_Plugin_Minecraft/pull/15) gets merged into the official plugin by @TouwaStar, you can use [this zip](https://github.com/TouwaStar/Galaxy_Plugin_Minecraft/files/5791138/minecraft_v1.0.3_hotfix.zip) (packaged plugin) if you'd like: [minecraft_v1.0.3_hotfix.zip](https://github.com/TouwaStar/Galaxy_Plugin_Minecraft/files/5791138/minecraft_v1.0.3_hotfix.zip)

_PR: #15_
