### ISSUE TITLE
[Suggestion] Universal Support

### ISSUE THREAD

**Issue by JustArion** [TouwaStar/Galaxy_Plugin_Minecraft#20]
Reliance on a third-party app breaks some of the trust thats instilled in GoG when third party apps are used to track progress. Supply chain attacks can occur and this places the end-user at risk. Local .exe location is not allowed by the plugin despite multiple modded minecrafts utilizing non %appdata% .minecraft locations, take Curseforge for example. Third party app reliance places a burden on the end user and degrades the experience of having a minecraft connection on the GoG client. The suggestion is to either use a user input .exe location or to scan the processes active and instruct the user to add a connection while minecraft is open and then get that location.

**Comment by urwrstkn8mare** [comment]
I'm pretty sure this plugin is only intended to integrate with Mojang's official launchers and I just added an optional simple MultiMC integration. If you want to run a `.exe`, I would think it simple enough just to use GOG Galaxy's built-in executable linking. Interesting suggestion tho.
