### ISSUE TITLE
Import game time from MultiMC

### ISSUE THREAD

**Issue by LividJava** [TouwaStar/Galaxy_Plugin_Minecraft#22]
I'd like to see if at all possible the import of game time if at all possible.

This may be a bit difficult as the total game times are fragmented across each instance folder, and I can see issues arising when people have numerous instances. The information is under the .cfg file per instance. (I believe the path is `MULTIMCINSTALLDIR/Instances/INSTANCENAME/instance.cfg` on line 43ish depending on instance configs) This is really a moonshot idea but if possible it'd be cool to see how much time I've wasted on games as a whole.

**Comment by urwrstkn8mare** [comment]
Is this not already the case? I remember implementing this. Please tell me of there's any issues with it.

**Comment by LividJava** [comment]
It isn't importing any gametime that I'm aware of. I literally played yesterday and nada
![image](https://user-images.githubusercontent.com/7604544/142271273-b0e157ef-09fd-49c1-b760-c90ef19a1760.png)

**Comment by urwrstkn8mare** [comment]
If you don't mind could I see your `instance.cfg`? Feel free to redact any personal information you have in their for whatever reason.

**Comment by urwrstkn8mare** [comment]
Also could I see the plugin's logs in `%programdata%\GOG.com\Galaxy\logs` . It'll have `minecraft` in it's filename.

**Comment by LividJava** [comment]
Alright here's the [gist](https://gist.github.com/LividJava/75047439357a02baacbe27f85244d878) for all the relevant files? there were 4 log files with minecraft so i just included all of them

**Comment by urwrstkn8mare** [comment]
From what it looks like the plugin never tried to get the time meaning GOG Galaxy never told the plugin to. Could you try pressing the `Sync integrations` button and/or `Exit`ing the client and starting it again. 

Reference: 
![Screenshot 2021-11-18 130845](https://user-images.githubusercontent.com/42769125/142355564-22cc2319-05b5-4ae4-8c02-43547110f669.png)

**Comment by LividJava** [comment]
I ended up just uninstalling the default launcher and it worked??
![image](https://user-images.githubusercontent.com/7604544/142360540-821c33cc-c96e-430d-8f6b-fa7459196005.png)

**Comment by LividJava** [comment]
I ended up just uninstalling the default launcher and it worked??
![image](https://user-images.githubusercontent.com/7604544/142360540-821c33cc-c96e-430d-8f6b-fa7459196005.png)

**Comment by urwrstkn8mare** [comment]
Oh that's odd. At least it works now. If you want the default launcher I'd recommend trying to install again and reconnecting the plugin in case it was a one off issue or install it through the Microsoft Store which makes it accessible through GOG Galaxy's official XBOX plugin.
