### ISSUE TITLE
Minecraft doesn't track my time

### ISSUE THREAD

**Issue by ARE2KUSU** [TouwaStar/Galaxy_Plugin_Minecraft#24]
Since the start that I use the plugin, it doesn't track my time.
I've installed the plugin and install the game by GOG 2.0.
I only have one minecraft installed.
But my friend seems to have the same configuration as me but have his time tracked. 
Please take a look at the screenshots below.

I don't know if it's an issue or a wrong configuration. Please tell me.

![myhours](https://user-images.githubusercontent.com/36100065/174737229-046b6229-6669-4db2-946b-b9945782fa13.png)

![firend hours](https://user-images.githubusercontent.com/36100065/174737225-1851127b-2c42-46c0-a511-1dbbcdd3cd4a.png)

**Comment by urwrstkn8mare** [comment]
@ARE2KUSU would you be able to provide some log files? Feel free to redact whatever you need to but that would help alot.

**Comment by ARE2KUSU** [comment]
@urwrstkn8mare, I just want Minecraft to track my time as integration my friend have, does. Here is my log files:

Minecraft one: 
[plugin-minecraft-cb57391f-1675-35b1-05c0-896d43bdf8f4.log](https://github.com/TouwaStar/Galaxy_Plugin_Minecraft/files/8954854/plugin-minecraft-cb57391f-1675-35b1-05c0-896d43bdf8f4.log)
[plugin-minecraft-cb57391f-1675-35b1-05c0-896d43bdf8f4-1.log](https://github.com/TouwaStar/Galaxy_Plugin_Minecraft/files/8954855/plugin-minecraft-cb57391f-1675-35b1-05c0-896d43bdf8f4-1.log)
[plugin-minecraft-cb57391f-1675-35b1-05c0-896d43bdf8f4-2.log](https://github.com/TouwaStar/Galaxy_Plugin_Minecraft/files/8954857/plugin-minecraft-cb57391f-1675-35b1-05c0-896d43bdf8f4-2.log)
[plugin-minecraft-cb57391f-1675-35b1-05c0-896d43bdf8f4-3.log](https://github.com/TouwaStar/Galaxy_Plugin_Minecraft/files/8954856/plugin-minecraft-cb57391f-1675-35b1-05c0-896d43bdf8f4-3.log)
[plugin-minecraft-cb57391f-1675-35b1-05c0-896d43bdf8f4-4.log](https://github.com/TouwaStar/Galaxy_Plugin_Minecraft/files/8954860/plugin-minecraft-cb57391f-1675-35b1-05c0-896d43bdf8f4-4.log)
[plugin-minecraft-cb57391f-1675-35b1-05c0-896d43bdf8f4-5.log](https://github.com/TouwaStar/Galaxy_Plugin_Minecraft/files/8954861/plugin-minecraft-cb57391f-1675-35b1-05c0-896d43bdf8f4-5.log)


Client one: 
[GalaxyClient.log](https://github.com/TouwaStar/Galaxy_Plugin_Minecraft/files/8954953/GalaxyClient.log)

**Comment by urwrstkn8mare** [comment]
Thank you for the files. Does your friend use MultiMC by any chance? Because otherwise the play time will only show time played minecarft when launched from GOG Galaxy.

**Comment by ARE2KUSU** [comment]
@urwrstkn8mare he doesn't use the MultiMC. I launch Minecraft from GOG every time.

**Comment by urwrstkn8mare** [comment]
There seems to be something wrong with the cache file. Could you please send the file at `C:\Users\ARE2KUSU\AppData\Local\GOG.com\Galaxy\plugins\installed\minecraft_play_time_cache.txt`. 

Also to fix the problem as soon as possible, delete the file **after** sending it. Make sure before doing that you completely close GOG Galaxy (so it's not I'm the dock either) and after deleting the file open GOG Galaxy again and click the sync integration button.  If you want you can also disconnect and reconnect the plugin. Then run Minecraft and make sure the play button is greyed in GOG Galaxy for at least 15 to 60 minutes. Then sync integration again and sync integration again. 

This is just so I can cover all the bases as hopefully just one of these solutions solve the problem. Plus this is hopefully just one time and the problem should go away as usually the plugin does show run time as you've observed. 

Sorry for the block of text but hopefully your issue goes away.

**Comment by ARE2KUSU** [comment]
@urwrstkn8mare Thank you. Here is my file : [minecraft_play_time_cache.txt](https://github.com/TouwaStar/Galaxy_Plugin_Minecraft/files/8965105/minecraft_play_time_cache.txt)

I try, but now my game don't start by clicking on play button. Before it was working. No idea what I've done wrong.
In order, I exit GOG, removed `minecraft_play_time_cache.txt`, removed integration, uninstall Minecraft from GOG, reboot then installing integration, installing Minecraft from GOG again, and sync integrations.
And my game don't start + the play button doesn't even turn to gray even few seconds.
Here are my logs : 
[GalaxyClient.log](https://github.com/TouwaStar/Galaxy_Plugin_Minecraft/files/8965299/GalaxyClient.log)
[plugin-minecraft-cb57391f-1675-35b1-05c0-896d43bdf8f4.log](https://github.com/TouwaStar/Galaxy_Plugin_Minecraft/files/8965333/plugin-minecraft-cb57391f-1675-35b1-05c0-896d43bdf8f4.log)

**Comment by urwrstkn8mare** [comment]
Interesting, the logs show that for a little time it thought it wasn't installed. I'm pretty confused on what's going on, but I won't give up. Btw, did you try disconnecting and reconnecting the plugin? When reconnecting, follow the prompts and then do the usual sync integration play for a bit and see. 

You could also try comparing your and your friend's setups in detail to see anything that is differing. Also have you tried to get him to help as well as there's only so much I can do over a GitHub thread.

**Comment by ARE2KUSU** [comment]
I've tried without any success, the game still not launch by GOG for now. I saw in the log this:
```
2022-06-23 12:04:34,485 - galaxy.task_manager - DEBUG - Task manager plugin external: creating task 23 (Update Task)
2022-06-23 12:04:34,485 - local - DEBUG - folder path for mc: C:\Program Files (x86)
2022-06-23 12:04:34,485 - local - DEBUG - path for mc: C:\Program Files (x86)\MinecraftLauncher.exe
2022-06-23 12:04:34,485 - galaxy.task_manager - DEBUG - Task manager plugin external: finished task 23 (Update Task)
2022-06-23 12:04:35,491 - galaxy.task_manager - DEBUG - Task manager plugin external: creating task 24 (Update Task)
```
But my game is stored here `C:\Program Files (x86)\Minecraft Launcher\MinecraftLauncher.exe`

I moved MinecraftLauncher.exe to  C:\Program Files (x86) it launches from GOG (with some error because I don't move the whole folder).

**Comment by urwrstkn8mare** [comment]
Oh ok, that's interesting. Looks like a registry issue. Are you able to reinstall Minecraft? Hoping reinstalling it gets Minecraft to clean up it's registry entries. If you know how to browse the registry and edit it, feel free to look at the keys the plugin looks at (screenshot and send here if you want):
```
HKEY_CURRENT_USER\SOFTWARE\Mojang\Minecraft Launcher
HKEY_CURRENT_USER\SOFTWARE\WOW6432Node\Mojang\Minecraft Launcher
HKEY_LOCAL_MACHINE\SOFTWARE\Mojang\Minecraft Launcher
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Mojang\Minecraft Launcher
```

**Comment by ARE2KUSU** [comment]
OK, I've already uninstalling and reinstalling it does nothing. I edited registry `HKEY_CURRENT_USER\SOFTWARE\Mojang\Minecraft Launcher`  and now I'm able to launch it by GOG. I'll try to do the previous step now.
![Capture d’écran 2022-06-23 122111](https://user-images.githubusercontent.com/36100065/175277581-a619f7ad-8193-43fc-b08e-988124a512bb.png)

**Comment by ARE2KUSU** [comment]
My time is tracking now.
Thank you :) 
![image](https://user-images.githubusercontent.com/36100065/175280772-327e3c44-73a8-43ff-b32c-fc8c04cf8e14.png)

**Comment by urwrstkn8mare** [comment]
Nw happy to help!
