### ISSUE TITLE
Minecraft Launcher not launching

### ISSUE THREAD

**Issue by LiborVojtek** [TouwaStar/Galaxy_Plugin_Minecraft#25]
I just connected this plugin and it does not launch the launcher.
Launching it directly or from shortcut predictably works.

Hitting the Play button gives You just the classic message "we are launching Minecraft", but then absolutely nothing happens.
I tried to re-install Minecraft Launcher, re-connecting the account, but nothing helped.

I have the GOG Galaxy 2.0.51 and Minecraft Launcher Windows version 2.3.240.

**Comment by urwrstkn8mare** [comment]
It seems like you're using the new Minecraft Launcher (see #21) from the Microsoft Store, this can be handled by the XBOX plugin for GOG Galaxy (an official plugin as well). If you're using the older launcher not from the Microsoft Store or MultiMC, this plugin can handle that. In fact, you can have both the Xbox plugin and the Minecraft plugin handling Minecraft at the same time, GOG Galaxy will allow you to switch between them and set defaults.

**Comment by LiborVojtek** [comment]
Thank You, that worked.
