### ISSUE TITLE
FOG Fork Autoupdate Request

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [TouwaStar/Galaxy_Plugin_Minecraft#3]
Hey,

we're planning on creating a fork/autoupdate system with selected plugins. This would allow us to create a list of curated and reviewed plugins which could be of use to GOG Galaxy people.

Of course you will be credited as the creator and developer of the plugin in the fork readme and possibly other places.

Before we do that we need to ask you to create a fog_release branch which would contain only your plugin code, manifest.json and a requirements.txt file (without 3rdparty directory). For Github releases, we will include whole directory where manifest.json is placed and build dependencies directly there. This is for easier code verification. Code for repo synchronization can be found here: https://github.com/FriendsOfGalaxy/galaxy-integrations-updater

**Comment by TouwaStar** [comment]
Here you go https://github.com/TouwaStar/Galaxy_Plugin_Minecraft/tree/fog_release
