### ISSUE TITLE
Minecraft installdir registry location

### ISSUE THREAD

**Issue by timster01** [TouwaStar/Galaxy_Plugin_Minecraft#4]
On my Pc the installdir key is in the registry in path Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Mojang\Minecraft
Also the keys that are there are InstallDir and InstallDirNew with InstallDirNew containing the actual location. I don't know if this is an old style of registry key but the plugin forces me to install minecraft due to this when it is already installed. Could the plugin also query these locations?

**Comment by timster01** [comment]
A solution could be that the user could specify a folder when connecting the plugin similar to connecting to steam for example where the user gets a login screen.

**Comment by urwrstkn8mare** [comment]
yes that happens to me as well, I'm just manually adding it now

**Comment by TouwaStar** [comment]
should be fixed in 0.8 released today

**Comment by timster01** [comment]
From what I can see the consts you used for this haven't changed. It also seems like gog is now picking up my minecraft java edition install without the plugin.

**Comment by TouwaStar** [comment]
they did https://github.com/TouwaStar/Galaxy_Plugin_Minecraft/commit/a5aa441affc85016b37d72d334969c72c36ea898

gog doesnt pick up anything by itself

**Comment by timster01** [comment]
I didn't check the commit so I didn't really understand the change without the context of the change to hkey current user. I must have added the minecraft launcher manually then without remembering.
