### ISSUE TITLE
make fog_release default

### ISSUE THREAD

**Issue by urwrstkn8mare** [TouwaStar/Galaxy_Plugin_Minecraft#9]
Just saying you can make `fog_release` the default branch which is more convenient. (in repo settings)

**Comment by urwrstkn8mare** [comment]
It is under `settings/branches`
![image](https://user-images.githubusercontent.com/42769125/92229370-f2fae980-eedb-11ea-8633-13c015269d0a.png)

**Comment by TouwaStar** [comment]
Thanks!
